// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Vnvc.Migrations
{
    [DbContext(typeof(VNVCContext))]
    partial class VNVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Core.Entities.VNVCModels.CHI_NHANH", b =>
                {
                    b.Property<string>("CN_ID")
                        .HasColumnType("nvarchar");

                    b.Property<string>("CN_DIACHI")
                        .HasColumnType("nvarchar");

                    b.Property<string>("CN_IDTINH")
                        .HasColumnType("nvarchar");

                    b.Property<string>("CN_TENCN")
                        .HasColumnType("nvarchar");

                    b.Property<string>("CN_IDTINH")
                        .HasColumnType("nvarchar");

                    b.HasKey("CN_ID");

                    b.HasIndex("TINH_THANHTT_ID");

                    b.ToTable("chiNhanh");
                });

            modelBuilder.Entity("Core.Entities.VNVCModels.CHI_TIET_DON_HANG", b =>
                {
                    b.Property<int>("CTDH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CTDH_GIA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CTDH_IDDH")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CTDH_IDSP")
                        .HasColumnType("nvarchar");

                    b.Property<int>("CTDH_SL")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CTDH_TENSP")
                        .HasColumnType("nvarchar");

                    b.Property<int?>("CTDH_IDDH")
                        .HasColumnType("INTEGER");

                    b.HasKey("CTDH_ID");

                    b.HasIndex("DON_HANGDH_ID");

                    b.ToTable("cTietDonHang");
                });

            modelBuilder.Entity("Core.Entities.VNVCModels.DON_HANG", b =>
                {
                    b.Property<int>("DH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CHI_NHANHCN_ID")
                        .HasColumnType("nvarchar");

                    b.Property<string>("DH_IDCN")
                        .HasColumnType("nvarchar");

                    b.Property<int>("DH_IDKH")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DH_NGAY")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DH_NGAYTIEM")
                        .HasColumnType("TEXT");

                    b.Property<int>("DH_TONGTIEN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DH_TTRANG")
                        .HasColumnType("nvarchar");

                    b.Property<int?>("DH_IDKH")
                        .HasColumnType("INTEGER");

                    b.HasKey("DH_ID");

                    b.HasIndex("CHI_NHANHCN_ID");

                    b.HasIndex("KHACH_HANGId");

                    b.ToTable("donHang");
                });

            modelBuilder.Entity("Core.Entities.VNVCModels.KHACH_HANG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KH_CCCD")
                        .HasColumnType("nvarchar");

                    b.Property<string>("KH_DIACHI")
                        .HasColumnType("nvarchar");

                    b.Property<string>("KH_EMAIL")
                        .HasColumnType("nvarchar");

                    b.Property<string>("KH_HOTEN")
                        .HasColumnType("nvarchar");

                    b.Property<string>("KH_ID")
                        .HasColumnType("nvarchar");

                    b.Property<string>("KH_SDT")
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("khachHang");
                });

            modelBuilder.Entity("Core.Entities.VNVCModels.TINH_THANH", b =>
                {
                    b.Property<string>("TT_ID")
                        .HasColumnType("nvarchar");

                    b.Property<string>("TT_TENTT")
                        .HasColumnType("nvarchar");

                    b.HasKey("TT_ID");

                    b.ToTable("tinhThanh");
                });

            modelBuilder.Entity("Core.Entities.VNVCModels.VIP", b =>
                {
                    b.Property<int>("VIP_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KHACH_HANGId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VIP_IDKH")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VIP_NGAYBD")
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("VIP_NGAYKT")
                        .HasColumnType("datetime");

                    b.HasKey("VIP_ID");

                    b.HasIndex("KHACH_HANGId");

                    b.ToTable("vips");
                });

            modelBuilder.Entity("Core.Entities.VNVCModels.CHI_NHANH", b =>
                {
                    b.HasOne("Core.Entities.VNVCModels.TINH_THANH", "TINH_THANH")
                        .WithMany()
                        .HasForeignKey("CN_IDTINH");

                    b.Navigation("TINH_THANH");
                });

            modelBuilder.Entity("Core.Entities.VNVCModels.CHI_TIET_DON_HANG", b =>
                {
                    b.HasOne("Core.Entities.VNVCModels.DON_HANG", "DON_HANG")
                        .WithMany()
                        .HasForeignKey("CTDH_IDDH");

                    b.Navigation("DON_HANG");
                });

            modelBuilder.Entity("Core.Entities.VNVCModels.DON_HANG", b =>
                {
                    b.HasOne("Core.Entities.VNVCModels.CHI_NHANH", "CHI_NHANH")
                        .WithMany()
                        .HasForeignKey("DH_IDCN");

                    b.HasOne("Core.Entities.VNVCModels.KHACH_HANG", "KHACH_HANG")
                        .WithMany()
                        .HasForeignKey("DH_IDKH");

                    b.Navigation("CHI_NHANH");

                    b.Navigation("KHACH_HANG");
                });

            modelBuilder.Entity("Core.Entities.VNVCModels.VIP", b =>
                {
                    b.HasOne("Core.Entities.VNVCModels.KHACH_HANG", "KHACH_HANG")
                        .WithMany()
                        .HasForeignKey("VIP_IDKH");

                    b.Navigation("KHACH_HANG");
                });
#pragma warning restore 612, 618
        }
    }
}
